services:
  airtfast_app:
    build: .
    container_name: airtfast_app_container
    restart: unless-stopped
    ports:
      - "5000:5005" 
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db_service:5432/mydatabase
    depends_on:
      db_service: # Changed from - db_service to db_service:
        condition: service_healthy # <--- ADD THIS LINE
    volumes:
      - .:/app

  db_service:
    image: postgres:13-alpine
    container_name: airtfast_db_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck: # <--- ADD THIS WHOLE BLOCK
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Gives the DB a grace period to start its internal initialization

volumes:
  db_data: